apiVersion: v1
kind: configMap
metadata:
  name: mongodb-config
  namespace: exam
data:
  host: mongodb-service
  dbname: exam
  authSource: admin
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: exam
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000 
  selector:
    app: backend
---
apiVersion: v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
    template:
      metadata:
        labels:
          app: backend
      spec:
        containers:
        - name: backend
          image: adamelkt/k8s_backend:1.0.0
          ports:
          - containerPort: 5000
          env:
            - name: DB_HOST
                valueFrom: 
                  configMapKeyRef: 
                    name: mongodb-config
                      key: host
            - name: DB_NAME
                valueFrom: 
                  configMapKeyRef: 
                    name: mongodb-config
                      key: db_name
            - name: AUTH_SOURCE
                valueFrom: 
                  configMapKeyRef: 
                    name: mongodb-config
                      key: authSource
            - name: DB_USERNAME
                valueFrom: 
                  secretKeyRef: 
                    name: mongodb-secret
                      key: username
            - name: DB_PWD
                valueFrom: 
                  secretKeyRef: 
                    name: mongodb-secret
                      key: password
